export { default as Header } from './Header/Header'
export { default as Introduction } from './Introduction/Introduction'
export { default as Shortener } from './Shortener/Shortener'
export { default as Statistics } from './Statistics/Statistics'
export { default as CallToAction } from './CallToAction/CallToAction'
export { default as Footer } from './Footer/Footer'
